#!/bin/bash
# Sync time on startup
sudo ntpdate -u pool.ntp.org &
/opt/mt-os/set-wallpaper.sh &
picom &
conky &
lxpanel --profile mt-os &
# mt-face.py is started by mt-ai-daemon.service
sleep 3 && python3 /opt/mt-os/mt-terminal.py &
pulseaudio --start &
dunst &
bash /opt/mt-os/update-checker.sh &
